
package nl.match_online.webservice.customer.v0p7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import fec.florecom.xml.data.draft.orderstandardmessage._7.OrderRequestMessage;
import fec.florecom.xml.data.draft.orderstandardmessage._7.OrderResponseMessage;
import fec.florecom.xml.data.draft.supplystandardmessage._7.SupplyRequestMessage;
import fec.florecom.xml.data.draft.supplystandardmessage._7.SupplyResponseMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommercialCustomer", targetNamespace = "http://webservice.florecom.org/CommercialCustomer")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    fec.florecom.xml.data.draft.orderstandardmessage._7.ObjectFactory.class,
    fec.florecom.xml.data.draft.supplystandardmessage._7.ObjectFactory.class,
    fc.florecom.xml.data.draft.unqualifieddatatype._1.ObjectFactory.class,
    fec.florecom.xml.data.draft.qualifieddatatype._7.ObjectFactory.class,
    fec.florecom.xml.data.draft.reusableaggregatebusinessinformationentity._6.ObjectFactory.class,
    un.unece.uncefact.data.standard.qualifieddatatype._3.ObjectFactory.class,
    un.unece.uncefact.data.standard.qualifieddatatype._7.ObjectFactory.class,
    un.unece.uncefact.data.standard.reusableaggregatebusinessinformationentity._3.ObjectFactory.class,
    un.unece.uncefact.data.standard.unqualifieddatatype._4.ObjectFactory.class,
    un.unece.uncefact.identifierlist.standard._5.iso316612a.secondedition2006vi_6.ObjectFactory.class,
    un.unece.uncefact.codelist.standard.unece.pricetypecode.d09a.ObjectFactory.class,
    un.unece.uncefact.codelist.standard._5.iso42173a._2007_06_18.ObjectFactory.class,
    fc.florecom.xml.codelist.draft.positionusage._1._0.ObjectFactory.class,
    un.unece.uncefact.identifierlist.standard._5.iso316612a.secondedition2006.ObjectFactory.class,
    fc.florecom.xml.codelist.draft.imagecategory._1._0.ObjectFactory.class,
    fc.florecom.xml.codelist.draft.imagesubject._1._0.ObjectFactory.class
})
public interface CommercialCustomer {


    /**
     * 
     * @param supplyRequest
     * @return
     *     returns fec.florecom.xml.data.draft.supplystandardmessage._7.SupplyResponseMessage
     */
    @WebMethod(operationName = "GetSupply", action = "http://webservices.florecom.org/commercial/customer/GetSupply_0p7")
    @WebResult(name = "SupplyResponse", targetNamespace = "urn:fec:florecom:xml:data:draft:SupplyStandardMessage:7", partName = "GetSupplyResult")
    public SupplyResponseMessage getSupply(
        @WebParam(name = "SupplyRequest", targetNamespace = "urn:fec:florecom:xml:data:draft:SupplyStandardMessage:7", partName = "SupplyRequest")
        SupplyRequestMessage supplyRequest);

    /**
     * 
     * @param putOrderRequest
     * @return
     *     returns fec.florecom.xml.data.draft.orderstandardmessage._7.OrderResponseMessage
     */
    @WebMethod(operationName = "PutOrder", action = "http://webservices.florecom.org/commercial/customer/PutOrder_0p7")
    @WebResult(name = "PutOrderResponse", targetNamespace = "urn:fec:florecom:xml:data:draft:OrderStandardMessage:7", partName = "PutOrderResult")
    public OrderResponseMessage putOrder(
        @WebParam(name = "PutOrderRequest", targetNamespace = "urn:fec:florecom:xml:data:draft:OrderStandardMessage:7", partName = "PutOrderRequest")
        OrderRequestMessage putOrderRequest);

}
