
package nl.match_online.webservice.customer.v0p7;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Match-Online Virtual Marketplace for the Customer, based on the Florecom Webservices
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Match-Online_x0020_Virtual_x0020_Marketplace_x0020_for_x0020_Customers", targetNamespace = "http://webservice.match-online.nl/Customer/v0p7", wsdlLocation = "http://web11.veilingholambra.match-online.nl/Webservice/CCVMP/v0p7/Customer.asmx?wsdl")
public class MatchOnlineX0020VirtualX0020MarketplaceX0020ForX0020Customers
    extends Service
{

    private final static URL MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_WSDL_LOCATION;
    private final static WebServiceException MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_EXCEPTION;
    private final static QName MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_QNAME = new QName("http://webservice.match-online.nl/Customer/v0p7", "Match-Online_x0020_Virtual_x0020_Marketplace_x0020_for_x0020_Customers");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://web11.veilingholambra.match-online.nl/Webservice/CCVMP/v0p7/Customer.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_WSDL_LOCATION = url;
        MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_EXCEPTION = e;
    }

    public MatchOnlineX0020VirtualX0020MarketplaceX0020ForX0020Customers() {
        super(__getWsdlLocation(), MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_QNAME);
    }

    public MatchOnlineX0020VirtualX0020MarketplaceX0020ForX0020Customers(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_QNAME, features);
    }

    public MatchOnlineX0020VirtualX0020MarketplaceX0020ForX0020Customers(URL wsdlLocation) {
        super(wsdlLocation, MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_QNAME);
    }

    public MatchOnlineX0020VirtualX0020MarketplaceX0020ForX0020Customers(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_QNAME, features);
    }

    public MatchOnlineX0020VirtualX0020MarketplaceX0020ForX0020Customers(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MatchOnlineX0020VirtualX0020MarketplaceX0020ForX0020Customers(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommercialCustomer
     */
    @WebEndpoint(name = "CommercialCustomer")
    public CommercialCustomer getCommercialCustomer() {
        return super.getPort(new QName("http://webservice.match-online.nl/Customer/v0p7", "CommercialCustomer"), CommercialCustomer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommercialCustomer
     */
    @WebEndpoint(name = "CommercialCustomer")
    public CommercialCustomer getCommercialCustomer(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.match-online.nl/Customer/v0p7", "CommercialCustomer"), CommercialCustomer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_EXCEPTION!= null) {
            throw MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_EXCEPTION;
        }
        return MATCHONLINEX0020VIRTUALX0020MARKETPLACEX0020FORX0020CUSTOMERS_WSDL_LOCATION;
    }

}
